[gravity]
domain = "gravity"
host = 44143

[subscriber]
subscriberID = "mysql_transmitter"
subscriberName = "MySQL Transmitter"
stateStore = "./statestore"
workerCount = 4
chunkSize = 2048
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000

[bufferInput]
chunkSize = 100
timeout = 50
#unit: millisecond

[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 32773
secure = false
username = "test"
password = "1qazXSW@"
dbname = "gravity"
